name: LogicCheckGPT
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - blas=1.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - cfitsio=3.470
  - charls=2.2.0
  - dask-core=2023.11.0
  - dav1d=1.2.1
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.5.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numpy-base=1.26.2
  - openjpeg=2.4.0
  - openssl=3.0.12
  - python=3.10.13
  - readline=8.2
  - snappy=1.1.10
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - xz=5.4.5
  - yaml=0.2.5
  - zfp=1.0.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - accelerate==0.25.0
    - addict==2.4.0
    - aiofiles==23.2.1
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - altair==5.2.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - appdirs==1.4.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - bitsandbytes==0.41.3.post2
    - blessed==1.20.0
    - blis==0.7.11
    - braceexpand==0.1.7
    - catalogue==2.0.10
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpathlib==0.16.0
    - cloudpickle==2.2.1
    - confection==0.1.4
    - contourpy==1.2.0
    - cycler==0.12.1
    - cymem==2.0.8
    - cytoolz==0.12.2
    - dask==2023.11.0
    - decord==0.6.0
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - en-core-web-lg==3.7.1
    - en-core-web-md==3.7.1
    - en-core-web-sm==3.7.1
    - et-xmlfile==1.1.0
    - exceptiongroup==1.2.0
    - fastapi==0.105.0
    - ffmpy==0.3.1
    - filelock==3.13.1
    - fonttools==4.46.0
    - frozenlist==1.4.0
    - fschat==0.2.34
    - fsspec==2023.12.2
    - gitdb==4.0.11
    - gitpython==3.1.41
    - gpustat==1.1.1
    - gradio==3.44.4
    - gradio-client==0.5.1
    - h11==0.14.0
    - httpcore==1.0.2
    - httpx==0.25.2
    - huggingface-hub==0.19.4
    - idna==3.6
    - imagecodecs==2023.1.23
    - imageio==2.31.4
    - importlib-metadata==7.0.1
    - importlib-resources==6.1.1
    - iopath==0.1.10
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - kiwisolver==1.4.5
    - langcodes==3.3.0
    - lazy-loader==0.3
    - locket==1.0.0
    - markdown-it-py==3.0.0
    - markdown2==2.4.11
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - mdurl==0.1.2
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - multidict==6.0.4
    - murmurhash==1.0.10
    - networkx==3.1
    - nh3==0.2.15
    - nltk==3.8.1
    - numpy==1.26.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-ml-py==12.535.133
    - omegaconf==2.3.0
    - openai==0.28.0
    - opencv-python==4.8.0.76
    - openpyxl==3.1.2
    - orjson==3.9.10
    - packaging==23.1
    - pandas==2.1.4
    - partd==1.4.1
    - pathy==0.10.3
    - peft==0.7.1
    - pillow==10.0.1
    - pip==23.3.1
    - platformdirs==4.1.0
    - portalocker==2.8.2
    - preshed==3.0.9
    - progressbar2==4.3.2
    - prompt-toolkit==3.0.43
    - protobuf==3.20.3
    - psutil==5.9.6
    - pycocotools==2.0.7
    - pydantic==1.10.13
    - pydantic-core==2.14.5
    - pydub==0.25.1
    - pygments==2.17.2
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - python-utils==3.8.1
    - pytz==2023.3.post1
    - pywavelets==1.5.0
    - pyyaml==6.0.1
    - referencing==0.32.0
    - regex==2023.10.3
    - requests==2.31.0
    - rich==13.7.0
    - rpds-py==0.13.2
    - safetensors==0.4.1
    - scikit-image==0.20.0
    - scikit-learn==1.4.0
    - scipy==1.11.4
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - sentry-sdk==1.39.2
    - setproctitle==1.3.3
    - setuptools==68.0.0
    - shortuuid==1.0.11
    - six==1.16.0
    - smart-open==6.4.0
    - smmap==5.0.1
    - sniffio==1.3.0
    - spacy==3.7.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - srsly==2.4.8
    - starlette==0.27.0
    - supervision==0.6.0
    - svgwrite==1.4.3
    - tabulate==0.9.0
    - thinc==8.1.12
    - threadpoolctl==3.2.0
    - tifffile==2023.4.12
    - tiktoken==0.5.2
    - timm==0.9.12
    - tokenizers==0.15.0
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.13.1
    - torchvision==0.14.1
    - tqdm==4.66.1
    - transformers==4.36.1
    - transformers-stream-generator==0.0.4
    - typer==0.9.0
    - typing-extensions==4.9.0
    - tzdata==2023.3
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - visual-genome==1.1.1
    - wandb==0.16.2
    - wasabi==1.1.2
    - wavedrom==2.0.3.post3
    - wcwidth==0.2.5
    - weasel==0.3.4
    - webdataset==0.2.48
    - websockets==11.0.3
    - wheel==0.41.2
    - yapf==0.40.2
    - yarl==1.9.4
    - zipp==3.17.0